1.- Importar NumPy

In [2]:
import numpy as np

1.- Crear una matriz (ndarray)

In [10]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3.- Acceder a elementos individuales

In [6]:
elemento = matriz[1, 2]
print("Elemento:", elemento)

Elemento: 6


4.- Operaciones básicas

In [11]:
suma = matriz + 10
producto = matriz * 2
promedio = np.mean(matriz)
suma_columnas = np.sum(matriz, axis=0)

print("Suma:\n", suma)
print("Producto:\n", producto)
print("Promedio:", promedio)
print("Suma de columnas:\n", suma_columnas)

Suma:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Producto:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Promedio: 5.0
Suma de columnas:
 [12 15 18]


5.- Crear un rango de valores

In [18]:
rango = np.arange(0, 10, 2)

print("Rango:\n", rango)

Rango:
 [0 2 4 6 8]


6.- Crear matriz de ceros y unos

In [19]:
matriz_zeros = np.zeros((3, 4))
matriz_ones = np.ones((2, 3))

print("Matriz de ceros:\n", matriz_zeros)
print("Matriz de unos:\n", matriz_ones)

Matriz de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz de unos:
 [[1. 1. 1.]
 [1. 1. 1.]]


7.- Producto interno y externo

In [21]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
producto_interno = np.dot(vector_a, vector_b)
producto_externo = np.outer(vector_a, vector_b)

print("Producto interno:", producto_interno)
print("Producto externo:\n", producto_externo)

Producto interno: 32
Producto externo:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


8.- Álgebra lineal

In [22]:
matriz_a = np.array([[2, 3], [4, 5]])
matriz_b = np.array([[1, 0], [0, 1]])
producto_matricial = np.matmul(matriz_a, matriz_b)
inversa = np.linalg.inv(matriz_a)

print("Producto matricial:\n", producto_matricial)
print("Matriz inversa:\n", inversa)

Producto matricial:
 [[2 3]
 [4 5]]
Matriz inversa:
 [[-2.5  1.5]
 [ 2.  -1. ]]


9.- Generación de números aleatorios

In [23]:
numeros_aleatorios = np.random.rand(5)
matriz_aleatoria = np.random.randn(3, 3)

print("Números aleatorios:\n", numeros_aleatorios)
print("Matriz aleatoria:\n", matriz_aleatoria)

Números aleatorios:
 [0.18369743 0.44849504 0.2255744  0.41642439 0.46257079]
Matriz aleatoria:
 [[-0.09429026 -1.2285069   0.59012252]
 [-1.24698265 -0.51789314  0.91810428]
 [ 0.20791016 -0.81987606  0.87013872]]
